# Generated by Django 4.0.9 on 2023-07-08 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
import django_quill.fields
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique_for_date='publish')),
                ('body_v1', django_quill.fields.QuillField(blank=True, default='', null=True)),
                ('reklama', models.IntegerField(default=3)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('place_news', models.CharField(choices=[('main_news', 'Main News'), ('es_1', 'Easy News 1'), ('an_1', 'Inne 1')], default='Main News', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('tag', models.CharField(default='#crypto', max_length=250)),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[1920, 1080], upload_to='images')),
                ('category', models.CharField(choices=[('kryptowaluty', 'kryptowaluty'), ('nauka', 'nauka'), ('analiza', 'analiza'), ('metaverse', 'metaverse'), ('NFT', 'NFT'), ('regulacje', 'regulacje')], default='', max_length=50)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-publish',),
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
