# Generated by Django 4.0.9 on 2023-07-09 09:54

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook',
            name='description_long',
            field=django_quill.fields.QuillField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='ebook',
            name='description_short',
            field=django_quill.fields.QuillField(blank=True, default='', null=True),
        ),
    ]
