# Generated by Django 4.0.9 on 2023-07-12 10:38

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0002_ebook_description_long_ebook_description_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebook',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(upload_to='images', verbose_name='Image'),
        ),
    ]
