# Generated by Django 4.0.9 on 2023-07-12 11:28

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0003_alter_ebook_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebook',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[1920, 1080], upload_to='images'),
        ),
    ]
