# Generated by Django 4.0.9 on 2023-07-12 11:34

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0004_alter_ebook_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook',
            name='small_image',
            field=django_resized.forms.ResizedImageField(crop=None, default='', force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[390, 285], upload_to='images_small'),
        ),
    ]
