# Generated by Django 4.0.9 on 2023-07-16 16:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ebook', '0006_ebookemails'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebookemails',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
